---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"
  become: yes

- name: Inject hostname and aliases to hosts file
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
  become: yes
